version: '3'
services:
  angular:
    container_name: angular
    hostname: angular
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
